export const SUBSCRIPTION_FEATURES = {
  FREE: [
    { name: '25 message credits/month' },
    { name: '1 chatbot' },
    { name: '450,000 characters/chatbot' },
    { name: 'Embed on unlimited websites' },
    { name: 'Limit to 10 links to train on' },
    { name: 'Upload multiple files' },
    { name: 'View conversation history' },
    { name: 'Chatbots get deleted after 7 days of inactivity' },
  ],
  BASIC: [
    { name: '2,000 message credits/month' },
    { name: '2 chatbots' },
    { name: '11,000,000 characters/chatbot' },
    { name: 'Unlimited links to train on' },
    { name: 'Embed on unlimited websites' },
    { name: 'Upload multiple files' },
    { name: 'View conversation history' },
    { name: 'Capture leads' },
    { name: 'API access' },
    { name: 'Slack integration' },
    { name: 'Instagram integration' },
    { name: 'WordPress integration' },
    { name: 'Messenger integration' },
  ],
  STANDARD: [
    { name: '10,000 message credits' },
    { name: '5 chatbots' },
    { name: '11,000,000 characters/chatbot' },
    { name: 'Unlimited links to train on' },
    { name: 'Embed on unlimited websites' },
    { name: 'Upload multiple files' },
    { name: 'View conversation history' },
    { name: 'Capture leads' },
    { name: 'API access' },
    { name: 'Slack integration' },
    { name: 'Instagram integration' },
    { name: 'WordPress integration' },
    { name: 'WhatsApp integration' },
    { name: 'Messenger integration' },
  ],
  PREMIUM: [
    {
      name: '40,000 message credits/month included (Messages over the limit will use your OpenAI API Key)',
    },
    { name: '10 chatbots' },
    { name: '11,000,000 characters/chatbot' },
    { name: 'Unlimited links to train on' },
    { name: 'Embed on unlimited websites' },
    { name: 'Upload multiple files' },
    { name: 'View conversation history' },
    { name: 'Capture leads' },
    { name: 'API access' },
    { name: 'Slack integration' },
    { name: 'Instagram integration' },
    { name: 'WordPress integration' },
    { name: 'WhatsApp integration' },
    { name: 'Messenger integration' },
    { name: 'Option to Choose GPT-4' },
    { name: "Remove 'Powered by AtlasChat'" },
    { name: 'Use your own custom domains' },
  ],
};

export const SUBSCRIPTION_FEATURES_METADATA = {
  FREE: {
    characters_limit: 450000,
    chatbot: 1,
    chatbot_inactivity: 1,
    conversation_history: 1,
    credits: 25,
    embed: 1,
    links: 10,
    upload_multiple_files: 1,
  },
  BASIC: {
    characters_limit: 11000000,
    chatbot: 2,
    chatbot_inactivity: 1,
    conversation_history: 1,
    credits: 2000,
    embed: 1,
    links: 'unlimited',
    upload_multiple_files: 1,
  },
  STANDARD: {
    characters_limit: 11000000,
    chatbot: 5,
    chatbot_inactivity: 1,
    conversation_history: 1,
    credits: 10000,
    embed: 1,
    links: 'unlimited',
    upload_multiple_files: 1,
  },
  PREMIUM: {
    characters_limit: 11000000,
    chatbot: 10,
    chatbot_inactivity: 1,
    conversation_history: 1,
    credits: 45000,
    embed: 1,
    links: 'unlimited',
    upload_multiple_files: 1,
  },
};
